# Generated by Django 2.2 on 2021-05-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='created',
        ),
    ]
